# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

before_install:
  - wget https://github.com/nghttp2/nghttp2/releases/download/v1.25.0/nghttp2-1.25.0.tar.gz
  - tar xzf nghttp2-1.25.0.tar.gz
  - cd nghttp2-1.25.0/
  - ./configure --enable-lib-only --enable-shared --disable-static
  - make
  - sudo make install

install: pip install -U tox-travis

script: tox
